pipeline {
 agent any
    environment {
    IMAGE_NAME = 'enterprise_module/euerkaserver'
    IMAGE_TAG = 'latest'
    SERVICE_NAME = 'euerkaserver'
    SERVICE_DESCRIPTION = 'Eureka Server'
    SERVICE_DISPLAY_NAME = 'Eureka Server'
    SERVICE_DIRECTORY = 'Phase-1-Basic Service Build/euerkaserver'
   }
    stages {
            stage('Maven Clean') {
                steps {
                    dir("$SERVICE_DIRECTORY") {
                        bat 'mvn clean'
                    }
                }
            }
            stage('Run Tests') {
                steps {
                    dir("$SERVICE_DIRECTORY") {
                        bat 'mvn test'
                    }
                }
            }
            stage('Maven Build Jar') {
                steps {
                    dir("$SERVICE_DIRECTORY") {
                        bat 'mvn clean package -DskipTests'
                    }
                }
            }
            stage('Build Docker Image') {
                steps {
                    dir("$SERVICE_DIRECTORY") {
                        bat 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                    }
                }
            }
            stage('Run Container (Sanity Check)') {
                steps {
                    dir("$SERVICE_DIRECTORY") {
                        bat 'docker run -d --name $SERVICE_NAME -p 5555:5555 $IMAGE_NAME:$IMAGE_TAG'
                    }
                }
            }
            stage('Push To Docker Hub') {
                steps {
                    withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS')])
                    {
                        powershell '''
                        Write-Host "USER=$env:DOCKER_USER"

                        if($env:DOCKER_PASS){
                            Write-Host "PASS=PRESENT"
                        }else{
                            Write-Host "PASS=NULL"
                            exit 1
                        }

                        docker login -u $DOCKER_USER -p $DOCKER_PASS
                        docker push $IMAGE_NAME:$IMAGE_TAG

                        '''
                    }
                }
            }
    }

    post {
        always {
            dir("$SERVICE_DIRECTORY") {
                bat 'docker rm -f $SERVICE_NAME || exit 0'
            }
        }
    }
}